from __future__ import annotations

import logging
from datetime import datetime
from pathlib import Path
from typing import Any

from bot.config import PDF_RESULTS_DIR
from bot.formatting import esc, format_seconds

logger = logging.getLogger(__name__)

PDF_OUTPUT_DIR = PDF_RESULTS_DIR

try:
    from pypdf import PdfReader, PdfWriter
    from pypdf.annotations import FreeText as _FreeTextAnnot

    _HAS_PYPDF = True
except ImportError:
    PdfReader = None
    PdfWriter = None
    _FreeTextAnnot = None
    _HAS_PYPDF = False
    logger.warning('pypdf_not_available_pdf_generation_disabled')


def _ensure_output_dir() -> Path:
    PDF_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    return PDF_OUTPUT_DIR


def _sanitize_filename(name: str) -> str:
    return ''.join(c if c.isalnum() or c in ' _-.' else '_' for c in name).strip() or 'result'


def generate_result_pdf(
    attempt: dict[str, Any],
    questions: list[dict[str, Any]],
    answers: list[dict[str, Any]],
    user_name: str = 'User',
) -> str | None:
    if not _HAS_PYPDF:
        logger.warning('pypdf_not_installed_cannot_generate_pdf')
        return None

    try:
        out_dir = _ensure_output_dir()
        safe_name = _sanitize_filename(user_name)[:40]
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        filename = f'{safe_name}_{timestamp}.pdf'
        filepath = out_dir / filename

        writer = PdfWriter()
        page = writer.add_blank_page(612, 792)
        y = 750
        margin = 40
        line_h = 14

        def _add_text(text: str, size: int = 10):
            nonlocal page, y
            if y < 30:
                page = writer.add_blank_page(612, 792)
                y = 750
            annot = _FreeTextAnnot(
                text=text,
                rect=(margin, y - size - 2, 560, y + 4),
                font='Helvetica',
                font_size=f'{size}pt',
                font_color='000000',
                background_color=None,
            )
            page.add_annotation(annot)
            y -= line_h

        total = len(questions)
        correct = sum(1 for a in answers if a.get('is_correct'))
        percent = round((correct / total) * 100) if total else 0
        score = attempt.get('score', 0)
        completion = attempt.get('completion_seconds', 0)
        mode = attempt.get('mode', '')
        diff = attempt.get('difficulty', '')

        _add_text(f'SAT Quiz — Natijalar', 16)
        y -= 4
        _add_text('')
        _add_text(f'Foydalanuvchi: {esc(user_name)}', 13)
        _add_text(f'Ball: {score}/100', 13)
        _add_text(f"To\'g\'ri: {correct}/{total} ({percent}%)", 13)
        _add_text(f'Vaqt: {format_seconds(completion)}', 13)
        _add_text(f'Rejim: {mode} {diff}', 13)
        _add_text('')
        _add_text(f'Yaratilgan: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', 8)
        _add_text('')

        wrong = [a for a in answers if not a.get('is_correct')]
        if wrong:
            y -= 4
            _add_text('Xatolar:', 13)
            _add_text('')
            for a in wrong[:20]:
                idx = a['question_index']
                q = questions[idx] if idx < len(questions) else {}
                prompt = str(q.get('prompt', q.get('question', '')))
                _add_text(f'{idx + 1}. {esc(prompt)}', 10)
                _add_text(f'   Siz: {esc(a.get("selected_answer", ""))}', 10)
                _add_text(f"   To\'g\'ri: {esc(a.get('correct_answer', ''))}", 10)
                _add_text('', 10)

        _add_text('PDF generated by SAT Quiz Bot', 8)

        with open(filepath, 'wb') as f:
            writer.write(f)

        logger.info('pdf_generated path=%s', filepath)
        return str(filepath)

    except Exception:
        logger.exception('pdf_generation_failed')
        return None


def cleanup_old_pdfs(max_age_hours: int = 24):
    if not PDF_OUTPUT_DIR.exists():
        return
    now = datetime.now()
    for f in PDF_OUTPUT_DIR.iterdir():
        if f.is_file() and f.suffix == '.pdf':
            try:
                mtime = datetime.fromtimestamp(f.stat().st_mtime)
                if (now - mtime).total_seconds() > max_age_hours * 3600:
                    f.unlink()
                    logger.debug('cleaned_old_pdf path=%s', f)
            except Exception:
                pass
